[project]
name = "project1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.16"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy==2.2.1",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
    "ucimlrepo>=0.0.7",
]
